// Generated by CoffeeScript 1.6.3
Template.hello.greeting = function() {
  return "Welcome to pypisearch.";
};

Template.hello.events({
  'click input': function() {
    if (typeof console !== "undefined" && console !== null) {
      return console.log("You pressed the button");
    }
  }
});
